# syntax=docker/dockerfile:1
ARG PYTHON_VERSION=3.11
FROM python:${PYTHON_VERSION}-bookworm AS requirements_stage

ARG IRONSBOT_RUNTIME_EXTRA="qq-official"

WORKDIR /wheel

RUN python -m pip install --user uv

COPY ./pyproject.toml \
  ./uv.lock \
  /wheel/

RUN set -eu; \
    extra_args=""; \
    if [ -n "$IRONSBOT_RUNTIME_EXTRA" ]; then \
        extra_args="--extra $IRONSBOT_RUNTIME_EXTRA"; \
    fi; \
    python -m uv export --frozen --no-dev $extra_args \
        --format requirements.txt --output-file requirements.txt --no-hashes

# uv.lock, including any declared override, is the dependency authority. The
# export is complete, so pip must build exactly those artifacts without solving
# their metadata a second time.
RUN python -m pip wheel --no-deps --wheel-dir=/wheel --no-cache-dir --requirement ./requirements.txt

# The builder resolves the VCS dependency once and produces a local wheel. The
# runtime stage is offline, so make its requirement select that wheel instead of
# trying to clone the repository again.
RUN set -eu; \
    model_wheel="$(find /wheel -maxdepth 1 -type f -name 'seerapi_models-*.whl' -printf '%f\n')"; \
    test -n "$model_wheel"; \
    test "$(printf '%s\n' "$model_wheel" | wc -l)" -eq 1; \
    model_version="${model_wheel#seerapi_models-}"; \
    model_version="${model_version%%-*}"; \
    sed -i "s|^seerapi-models @ git+.*$|seerapi-models==${model_version}|" /wheel/requirements.txt; \
    grep -Fx "seerapi-models==${model_version}" /wheel/requirements.txt

RUN python - <<'PY'
import io
from pathlib import Path
import urllib.request
import zipfile

url = (
    "https://github.com/adobe-fonts/source-han-sans/releases/download/"
    "2.005R/19_SourceHanSansCN.zip"
)
with urllib.request.urlopen(url) as response:
    archive = zipfile.ZipFile(io.BytesIO(response.read()))

font_names = {
    "SourceHanSansCN-Regular.otf",
    "SourceHanSansCN-Bold.otf",
}
font_entries = {
    Path(name).name: name
    for name in archive.namelist()
    if Path(name).name in font_names
}
if font_entries.keys() != font_names:
    raise RuntimeError(f"unexpected Source Han Sans CN archive: {font_entries}")

font_dir = Path("/tmp/fonts")
font_dir.mkdir(parents=True)
for filename, entry in font_entries.items():
    (font_dir / filename).write_bytes(archive.read(entry))

license_entry = next(
    (name for name in archive.namelist() if Path(name).name == "LICENSE.txt"),
    None,
)
if license_entry is None:
    raise RuntimeError("Source Han Sans CN archive has no LICENSE.txt")
license_dir = Path("/tmp/font-license")
license_dir.mkdir(parents=True)
(license_dir / "LICENSE.txt").write_bytes(archive.read(license_entry))
PY


FROM python:${PYTHON_VERSION}-slim-bookworm

ARG PYTHON_VERSION

WORKDIR /app

ARG IRONSBOT_PROJECT_URL=""
ENV TZ=Asia/Shanghai
ENV PYTHONPATH=/app
ENV IRONSBOT_PROJECT_URL=${IRONSBOT_PROJECT_URL}
# Keep generated bytecode out of the image and writable runtime mounts.
ENV PYTHONDONTWRITEBYTECODE=1
# Emit Python stack traces to container logs when a native extension crashes.
ENV PYTHONFAULTHANDLER=1

COPY --from=requirements_stage /tmp/fonts/ /usr/share/fonts/opentype/source-han-sans/
COPY --from=requirements_stage /tmp/font-license/LICENSE.txt /usr/share/doc/source-han-sans/LICENSE.txt
RUN apt-get update \
    && apt-get install -y --no-install-recommends fontconfig \
    && fc-cache -fv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# The container never installs packages at runtime. Keep its application
# dependencies, but remove Python's packaging toolchain from the final layer.
# Mount wheels for installation; copying then deleting them retains a large layer.
RUN --mount=type=bind,from=requirements_stage,source=/wheel,target=/wheel \
    pip install --no-deps --no-cache-dir --no-compile --no-index --find-links=/wheel -r /wheel/requirements.txt \
    && rm -rf /usr/local/lib/python${PYTHON_VERSION}/site-packages/pygments \
        /usr/local/lib/python${PYTHON_VERSION}/site-packages/pygments-*.dist-info \
        /usr/local/lib/python${PYTHON_VERSION}/site-packages/pymdownx \
        /usr/local/lib/python${PYTHON_VERSION}/site-packages/pymdown_extensions-*.dist-info \
        /usr/local/bin/pygmentize \
        /usr/local/lib/python${PYTHON_VERSION}/site-packages/pip \
        /usr/local/lib/python${PYTHON_VERSION}/site-packages/pip-*.dist-info \
        /usr/local/lib/python${PYTHON_VERSION}/site-packages/setuptools \
        /usr/local/lib/python${PYTHON_VERSION}/site-packages/setuptools-*.dist-info \
        /usr/local/lib/python${PYTHON_VERSION}/site-packages/wheel \
        /usr/local/lib/python${PYTHON_VERSION}/site-packages/wheel-*.dist-info \
        /usr/local/bin/pip \
        /usr/local/bin/pip3 \
        /usr/local/bin/pip${PYTHON_VERSION}

# Keep the runtime layer independent from repository-only material.  Tests,
# documentation, local data and build scripts are useful in source checkouts,
# but are never imported by the container process.
COPY ironsbot /app/ironsbot
COPY docker-entrypoint.sh __version__ config.example.toml /app/
COPY LICENSE LICENSE.GPL-3.0 LICENSING.md /app/

ENTRYPOINT ["sh", "/app/docker-entrypoint.sh"]
CMD ["python", "-m", "ironsbot"]
