# syntax=docker/dockerfile:1
FROM python:3.10 AS requirements_stage

WORKDIR /wheel

RUN python -m pip install --user uv

COPY ./pyproject.toml \
  ./uv.lock \
  /wheel/

RUN python -m uv export --frozen --no-dev --format requirements.txt --output-file requirements.txt --no-hashes

RUN python -m pip wheel --wheel-dir=/wheel --no-cache-dir --requirement ./requirements.txt

RUN python -c "\
import urllib.request, zipfile, io, os;\
os.makedirs('/tmp/fonts', exist_ok=True);\
url='https://github.com/adobe-fonts/source-han-sans/releases/download/2.005R/09_SourceHanSansSC.zip';\
data=urllib.request.urlopen(url).read();\
z=zipfile.ZipFile(io.BytesIO(data));\
[open(f'/tmp/fonts/{os.path.basename(n)}','wb').write(z.read(n)) for n in z.namelist() if n.endswith('.otf') and ('Regular' in n or 'Bold' in n)]"


FROM python:3.10-slim

WORKDIR /app

ENV TZ Asia/Shanghai
ENV PYTHONPATH=/app
# Keep generated bytecode out of the image and writable runtime mounts.
ENV PYTHONDONTWRITEBYTECODE=1
# Emit Python stack traces to container logs when a native extension crashes.
ENV PYTHONFAULTHANDLER=1

COPY --from=requirements_stage /tmp/fonts/ /usr/share/fonts/opentype/source-han-sans/
RUN apt-get update \
    && apt-get install -y --no-install-recommends fontconfig \
    && fc-cache -fv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# The container never installs packages at runtime. Keep its application
# dependencies, but remove Python's packaging toolchain from the final layer.
# Mount wheels for installation; copying then deleting them retains a large layer.
RUN --mount=type=bind,from=requirements_stage,source=/wheel,target=/wheel \
    pip install --no-cache-dir --no-compile --no-index --find-links=/wheel -r /wheel/requirements.txt \
    && rm -rf /usr/local/lib/python3.10/site-packages/pip \
        /usr/local/lib/python3.10/site-packages/pip-*.dist-info \
        /usr/local/lib/python3.10/site-packages/setuptools \
        /usr/local/lib/python3.10/site-packages/setuptools-*.dist-info \
        /usr/local/lib/python3.10/site-packages/wheel \
        /usr/local/lib/python3.10/site-packages/wheel-*.dist-info \
        /usr/local/bin/pip \
        /usr/local/bin/pip3 \
        /usr/local/bin/pip3.10

# Keep the runtime layer independent from repository-only material.  Tests,
# documentation, local data and build scripts are useful in source checkouts,
# but are never imported by the container process.
COPY ironsbot /app/ironsbot
COPY docker-entrypoint.sh __version__ config.example.toml /app/
COPY LICENSE LICENSE.GPL-3.0 LICENSING.md /app/

ENTRYPOINT ["sh", "/app/docker-entrypoint.sh"]
CMD ["python", "-m", "ironsbot"]
