# SPDX-License-Identifier: GPL-3.0-or-later

BOOK_RANK_KEY = 156
BOOK_RANK_SUB_KEY = 1
ACHIEVE_RANK_KEY = 17
ACHIEVE_RANK_SUB_KEY = 0

PET_KIND_RANK_KEY = 158
PET_KIND_RANK_SUB_KEY = 1
COUNTERMARK_RANK_KEY = 159
COUNTERMARK_RANK_SUB_KEY = 1
OUTFIT_RANK_KEY = 160
OUTFIT_SUIT_RANK_SUB_KEY = 1
OUTFIT_PART_RANK_SUB_KEY = 2
MOUNT_RANK_SUB_KEY = 3
SKIN_RANK_KEY = 161
SKIN_RANK_SUB_KEY = 1
AUTOCARD_RANK_KEY = 240
AUTOCARD_RANK_SUB_KEY = 1

STANDARD_PEAK_USER_RANK_KEY = 120
WILD_PEAK_USER_RANK_KEY = 182
EXPERT_PEAK_USER_RANK_KEY = 199
