# SPDX-License-Identifier: GPL-3.0-or-later
from __future__ import annotations

from pathlib import Path

IRONSBOT_PACKAGE_ROOT = Path(__file__).resolve().parents[2]

SEER_ASSETS_ROOT = IRONSBOT_PACKAGE_ROOT / "plugins" / "seer" / "assets"
SEER_ASSET_TEMPLATES_PATH = SEER_ASSETS_ROOT / "templates"
CUSTOM_PET_INFO_TEMPLATE_PATH = SEER_ASSET_TEMPLATES_PATH / "pet_info"

UPSTREAM_SEER_ASSETS_ROOT = SEER_ASSETS_ROOT / "_upstream"
UPSTREAM_SEER_INFO_TEMPLATES_PATH = UPSTREAM_SEER_ASSETS_ROOT / "templates"
UPSTREAM_SHARED_TEMPLATE_PATH = UPSTREAM_SEER_INFO_TEMPLATES_PATH / "_shared"
UPSTREAM_PET_INFO_TEMPLATE_PATH = UPSTREAM_SEER_INFO_TEMPLATES_PATH / "pet_info"
UPSTREAM_PET_INFO_IMAGES_PATH = UPSTREAM_PET_INFO_TEMPLATE_PATH / "images"
UPSTREAM_TYPE_MATCHUP_TEMPLATE_PATH = (
    UPSTREAM_SEER_INFO_TEMPLATES_PATH / "type_matchup"
)
UPSTREAM_PEAK_POOL_TEMPLATE_PATH = UPSTREAM_SEER_INFO_TEMPLATES_PATH / "peak_pool"
UPSTREAM_PEAK_POOL_VOTE_TEMPLATE_PATH = (
    UPSTREAM_SEER_INFO_TEMPLATES_PATH / "peak_pool_vote"
)
UPSTREAM_PEAK_PET_RANK_TEMPLATE_PATH = (
    UPSTREAM_SEER_INFO_TEMPLATES_PATH / "peak_pet_rank"
)

__all__ = [
    "CUSTOM_PET_INFO_TEMPLATE_PATH",
    "IRONSBOT_PACKAGE_ROOT",
    "SEER_ASSETS_ROOT",
    "SEER_ASSET_TEMPLATES_PATH",
    "UPSTREAM_PEAK_PET_RANK_TEMPLATE_PATH",
    "UPSTREAM_PEAK_POOL_TEMPLATE_PATH",
    "UPSTREAM_PEAK_POOL_VOTE_TEMPLATE_PATH",
    "UPSTREAM_PET_INFO_IMAGES_PATH",
    "UPSTREAM_PET_INFO_TEMPLATE_PATH",
    "UPSTREAM_SEER_ASSETS_ROOT",
    "UPSTREAM_SEER_INFO_TEMPLATES_PATH",
    "UPSTREAM_SHARED_TEMPLATE_PATH",
    "UPSTREAM_TYPE_MATCHUP_TEMPLATE_PATH",
]
