# SPDX-License-Identifier: GPL-3.0-or-later

PLAYER_ID_KEY = "player_id"
PLAYER_CONVERSATION_NAMESPACE = "seer_player"
PLAYER_DETAIL_NAMESPACE = PLAYER_CONVERSATION_NAMESPACE
PLAYER_BINDING_NAMESPACE = PLAYER_CONVERSATION_NAMESPACE
PLAYER_BINDING_PENDING_KEY = "_player_binding_pending"
PLAYER_QUERY_IS_EXPLICIT_KEY = "_player_query_is_explicit"
PLAYER_ERROR_FORMATTER_KEY = "_player_error_formatter"
