# SPDX-License-Identifier: MIT
from .conversations import (
    EventReplyCheck,
    command_reply_check,
    enter_event_reply_conversation,
    event_conversation_session_id,
)
from .query_guard import QueryGuard
from .rate_limits import (
    InMemoryRateLimiter,
    peek_user_rate_limit,
    penalize_user_rate_limit,
    rate_limiter,
)
from .replies import (
    BeforeReplySendHook,
    ReplyMessage,
    ReplyMessageLimiter,
    apply_reply_before_send,
    configure_reply_delivery_policy,
    event_sender_at_user_ids,
    finish_event_reply,
    finish_matcher_message,
    finish_message_sequence,
    limit_reply_message,
    send_event_reply,
    send_matcher_message,
)
from .reply_limits import (
    REPLY_LINE_LIMIT_CLEAR_COMMANDS,
    REPLY_LINE_LIMIT_COMMANDS,
    TEXT_ONLY_SEGMENT_TYPES,
    TEXT_SEND_APIS,
    ReplyLineLimitDecision,
    build_reply_line_limit_decision,
    can_manage_reply_line_limit,
    group_id_for_send_api,
    limit_onebot_message,
    limit_text_lines,
    parse_reply_line_limit_arg,
)
from .senders import (
    MessageLimiter,
    OneBotMessageSender,
    configure_sender_message_limiter,
    get_bot_or_none,
    send_broadcast_message,
    send_target_messages,
)
from .targets import (
    MessageTarget,
    TargetSendSummary,
    broadcast_targets,
    group_targets,
    private_targets,
)
from .text import (
    DEFAULT_COMMAND_PREFIXES,
    build_message,
    command_text_matches,
    normalize_command_text,
    render_text,
    strip_command_prefix,
)

__all__ = [
    "DEFAULT_COMMAND_PREFIXES",
    "EventReplyCheck",
    "InMemoryRateLimiter",
    "MessageLimiter",
    "MessageTarget",
    "OneBotMessageSender",
    "QueryGuard",
    "REPLY_LINE_LIMIT_CLEAR_COMMANDS",
    "REPLY_LINE_LIMIT_COMMANDS",
    "ReplyMessage",
    "ReplyMessageLimiter",
    "ReplyLineLimitDecision",
    "TEXT_ONLY_SEGMENT_TYPES",
    "TEXT_SEND_APIS",
    "TargetSendSummary",
    "apply_reply_before_send",
    "BeforeReplySendHook",
    "broadcast_targets",
    "build_message",
    "build_reply_line_limit_decision",
    "can_manage_reply_line_limit",
    "command_reply_check",
    "command_text_matches",
    "configure_reply_delivery_policy",
    "configure_sender_message_limiter",
    "enter_event_reply_conversation",
    "event_conversation_session_id",
    "event_sender_at_user_ids",
    "finish_event_reply",
    "finish_matcher_message",
    "finish_message_sequence",
    "get_bot_or_none",
    "group_id_for_send_api",
    "group_targets",
    "limit_onebot_message",
    "limit_reply_message",
    "limit_text_lines",
    "normalize_command_text",
    "parse_reply_line_limit_arg",
    "peek_user_rate_limit",
    "penalize_user_rate_limit",
    "private_targets",
    "rate_limiter",
    "render_text",
    "send_broadcast_message",
    "send_event_reply",
    "send_matcher_message",
    "send_target_messages",
    "strip_command_prefix",
]
