[tool.nonebot]
plugin_dirs = []

[tool.nonebot.plugins]
"@local" = [
  "nonebot_plugin_apscheduler",
  "nonebot_plugin_htmlkit",
  "ironsbot.plugins.onebot.scheduler",
  "ironsbot.plugins.onebot.seer.query",
  "ironsbot.plugins.onebot.about",
  "ironsbot.plugins.onebot.help",
  "ironsbot.plugins.onebot.help.hint",
  "ironsbot.plugins.onebot.seer.rank_help",
]
